/**
* ⚠️ AUTO-GENERATED FILE
*
* This file was generated by devops/generate-preview-code.ts.
* Do not modify this file directly — your changes will be overwritten.
*/
import { code } from "./code";
import { Preview } from "./Preview";

export const variant = {
  preview: Preview,
  code,
};